const S={role:null,user:null,page:"overview",voted:false,candidates:[{id:"C001",name:"Ananya Menon",category:"Candidate A",votes:42},{id:"C002",name:"Arjun Nair",category:"Candidate B",votes:35},{id:"C003",name:"Meera Thomas",category:"Candidate C",votes:28}],voters:[{id:"V001",name:"Aarav",voted:true},{id:"V002",name:"Diya",voted:false},{id:"V003",name:"Rahul",voted:true},{id:"V004",name:"Sana",voted:false}],audit:[["Vote recorded","V001 · Candidate C001","Today, 10:42"],["Candidate added","C003 · Meera Thomas","Today, 10:17"],["Voter authenticated","V001 · SHA-256 verification","Today, 10:12"],["Duplicate vote blocked","V003 · existing vote detected","Yesterday, 16:08"]]};
const menus={Admin:[["overview","▦","Overview"],["candidates","♙","Candidates"],["voters","♙","Voters"],["results","◒","Results"],["audit","◌","Audit log"]],Candidate:[["overview","▦","Overview"],["results","◒","Results"],["audit","◌","Audit log"]],Voter:[["overview","▦","Overview"],["vote","✓","Cast vote"],["results","◒","Results"]]};
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),init=s=>s.split(/\s+/).map(x=>x[0]).slice(0,2).join("").toUpperCase();
function toast(x){$("toast").textContent=x;$("toast").classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>$("toast").classList.remove("show"),2400)}
function nav(){$("nav").innerHTML=menus[S.role].map(x=>'<button class="nav '+(S.page===x[0]?"active":"")+'" data-p="'+x[0]+'"><i>'+x[1]+'</i>'+x[2]+'</button>').join("");document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{S.page=b.dataset.p;nav();render()})}
function head(a,b,c=""){return'<div class="head"><div><h2>'+a+'</h2><p>'+b+'</p></div><div>'+c+'</div></div>'}
function stats(items){return'<div class="grid stats">'+items.map(x=>'<div class="stat"><label>'+x[0]+'</label><strong>'+x[1]+'</strong><small>'+x[2]+'</small></div>').join("")+'</div>'}
function ranking(){let a=[...S.candidates].sort((x,y)=>y.votes-x.votes),m=Math.max(...a.map(x=>x.votes),1);return a.map((x,i)=>'<div class="rank"><b>0'+(i+1)+'</b><div><div class="name">'+esc(x.name)+'</div><div class="bar"><span style="width:'+(x.votes/m*100)+'%"></span></div></div><span class="votes">'+x.votes+'</span></div>').join("")}
function overview(){if(S.role==="Voter")return voterHome();if(S.role==="Candidate")return candidateHome();let total=S.candidates.reduce((a,c)=>a+c.votes,0),v=S.voters.filter(x=>x.voted).length;return head("Admin overview","Manage voters, candidates and the voting process.",'<button class="primary" onclick="addCandidateForm()">+ Add candidate</button>')+stats([["Registered voters",S.voters.length,"Eligible accounts"],["Candidates",S.candidates.length,"Active candidates"],["Votes recorded",total,"Across candidates"],["Participation",Math.round(v/S.voters.length*100)+"%",v+" voters have voted"]])+'<div class="grid two"><div class="card"><h3>Current ranking</h3><p class="sub">Live vote count and candidate ranking.</p>'+ranking()+'</div><div class="card"><h3>System controls</h3><div class="feature"><b>Security:</b> SHA-256 authentication, application + database duplicate prevention, audit logging and atomic transactions are planned backend responsibilities.</div><p class="sub" style="margin-top:15px">Database: SQLite · Access: JDBC · Application: Java</p></div></div>'}
function voterHome(){return head("Voter dashboard","Your voting access and election status.")+stats([["Your status",S.voted?"Submitted":"Not voted",S.voted?"Duplicate voting blocked":"One vote allowed"],["Candidates",S.candidates.length,"Choose one"],["Authentication","SHA-256","Backend requirement"],["Record","Atomic","Database transaction"]])+'<div class="grid two"><div class="card"><h3>Voting access</h3><p class="sub">Each voter can submit one vote.</p><div class="feature"><b>Status:</b> <span class="pill '+(S.voted?"ok":"warn")+'">'+(S.voted?"Vote submitted":"Ready to vote")+'</span><br><br>The production Java backend should persist the vote using JDBC and SQLite.</div><button class="primary" onclick="go(\'vote\')" '+(S.voted?"disabled":"")+'>'+(S.voted?"Vote already submitted":"Continue to voting")+'</button></div><div class="card"><h3>Security model</h3><p class="sub">Role-based controls for the voter.</p><div class="audit"><i class="dot"></i><div><b>Duplicate prevention</b><small>Application + database uniqueness.</small></div></div><div class="audit"><i class="dot"></i><div><b>Audit trail</b><small>Important actions are recorded.</small></div></div></div></div>'}
function candidateHome(){let c=S.candidates[0];return head("Candidate dashboard","View candidate status and live election results.")+stats([["Candidate ID",c.id,"Registered"],["Current votes",c.votes,"Live count"],["Status","Active","Eligible"],["Role","Candidate","Restricted menu"]])+'<div class="grid two"><div class="card"><h3>Candidate profile</h3><div class="candidate"><div class="avatar">'+init(c.name)+'</div><h3>'+esc(c.name)+'</h3><p>'+esc(c.category)+' · '+c.id+'</p></div></div><div class="card"><h3>Live ranking</h3>'+ranking()+'</div></div>'}
function candidates(){return head("Candidate management","Add and review registered candidates.",'<button class="primary" onclick="addCandidateForm()">+ Add candidate</button>')+'<div class="card"><table><thead><tr><th>ID</th><th>Candidate</th><th>Category</th><th>Votes</th><th>Status</th><th></th></tr></thead><tbody>'+S.candidates.map(c=>'<tr><td><b>'+c.id+'</b></td><td>'+esc(c.name)+'</td><td>'+esc(c.category)+'</td><td>'+c.votes+'</td><td><span class="pill ok">Active</span></td><td><button class="ghost" onclick="removeCandidate(\''+c.id+'\')">Remove</button></td></tr>').join("")+'</tbody></table></div>'}
function voters(){return head("Voter management","Monitor voter eligibility and one-vote participation.")+'<div class="card"><table><thead><tr><th>ID</th><th>Name</th><th>Eligibility</th><th>Vote status</th><th>Demo</th></tr></thead><tbody>'+S.voters.map(v=>'<tr><td><b>'+v.id+'</b></td><td>'+esc(v.name)+'</td><td><span class="pill ok">Eligible</span></td><td><span class="pill '+(v.voted?"neutral":"warn")+'">'+(v.voted?"Already voted":"Not voted")+'</span></td><td><button class="ghost" onclick="toggleVoter(\''+v.id+'\')">Toggle</button></td></tr>').join("")+'</tbody></table></div>'}
function vote(){if(S.voted)return head("Vote submitted","Your prototype vote has already been recorded.")+'<div class="card"><div class="feature"><b>Duplicate voting is disabled.</b><br>Your next attempt is blocked at the application layer; production must also enforce uniqueness in SQLite.</div></div>';return head("Cast your vote","Select one candidate and confirm your choice.")+'<div class="grid cards">'+S.candidates.map(c=>'<div class="candidate"><div class="avatar">'+init(c.name)+'</div><h3>'+esc(c.name)+'</h3><p>'+esc(c.category)+' · '+c.id+'</p><button class="primary" onclick="confirmVote(\''+c.id+'\')">Vote for '+esc(c.name)+'</button></div>').join("")+'</div>'}
function results(){let t=S.candidates.reduce((a,c)=>a+c.votes,0),top=[...S.candidates].sort((a,b)=>b.votes-a.votes)[0];return head("Live results","Current candidate ranking and vote totals.")+stats([["Total votes",t,"Recorded"],["Candidates",S.candidates.length,"Active"],["Top candidate",top.name,"Highest count"],["Counting","Live","Instant ranking"]])+'<div class="grid two"><div class="card"><h3>Candidate ranking</h3>'+ranking()+'</div><div class="card"><h3>Accuracy & integrity</h3><div class="feature">The specification requires accurate live counts and instant candidate ranking.</div><p class="sub" style="margin-top:15px">Atomic transactions protect incomplete database writes.</p></div></div>'}
function audit(){return head("Audit log","Accountability view for authentication and voting actions.")+'<div class="card"><h3>Recent activity</h3>'+S.audit.map(a=>'<div class="audit"><i class="dot"></i><div><b>'+esc(a[0])+'</b><small>'+esc(a[1])+'</small></div><time>'+esc(a[2])+'</time></div>').join("")+'</div>'}
function render(){let f={overview,candidates,voters,vote,results,audit}[S.page]||overview;$("content").innerHTML=f()}
function go(p){S.page=p;nav();render()}
function modal(html){$("modal").className="modal-bg";$("modal").innerHTML='<div class="modal-box">'+html+'</div>'}function closeModal(){$("modal").className="hidden";$("modal").innerHTML=""}
function addCandidateForm(){modal('<h3>Add candidate</h3><p>Prototype for the Admin manage-candidate requirement. Production insertion belongs in Java/JDBC/SQLite.</p><label>Name</label><input id="newName" placeholder="Candidate name"><label>Category</label><input id="newCat" placeholder="Candidate D"><div class="modal-actions"><button class="ghost" onclick="closeModal()">Cancel</button><button class="primary" onclick="addCandidate()">Add candidate</button></div>')}
function addCandidate(){let n=$("newName").value.trim(),cat=$("newCat").value.trim()||"Candidate";if(!n)return toast("Enter a candidate name.");let id="C"+String(S.candidates.length+1).padStart(3,"0");S.candidates.push({id:id,name:n,category:cat,votes:0});S.audit.unshift(["Candidate added","Prototype · "+n,"Just now"]);closeModal();render();toast("Candidate added.")}
function removeCandidate(id){S.candidates=S.candidates.filter(c=>c.id!==id);render();toast("Candidate removed.")}
function toggleVoter(id){let v=S.voters.find(x=>x.id===id);v.voted=!v.voted;render()}
function confirmVote(id){let c=S.candidates.find(x=>x.id===id);modal('<h3>Confirm your vote</h3><p>You selected <b>'+esc(c.name)+'</b>. Continue?</p><div class="modal-actions"><button class="ghost" onclick="closeModal()">Go back</button><button class="primary" onclick="submitVote(\''+id+'\')">Confirm vote</button></div>')}
function submitVote(id){if(S.voted)return;let c=S.candidates.find(x=>x.id===id);c.votes++;S.voted=true;S.audit.unshift(["Vote recorded","Prototype · "+id,"Just now"]);closeModal();go("vote");toast("Vote recorded successfully.")}
$("loginForm").onsubmit=e=>{e.preventDefault();let u=$("username").value.trim(),p=$("password").value;if(!u||!p){$("loginMsg").textContent="Enter username and password.";return}S.role=$("role").value;S.user=u;S.page="overview";$("login").classList.add("hidden");$("app").classList.remove("hidden");$("roleBadge").textContent=S.role;$("userName").textContent=u;nav();render()};
$("logout").onclick=()=>{S.role=null;S.user=null;$("app").classList.add("hidden");$("login").classList.remove("hidden");$("loginForm").reset();toast("Signed out.")};